local ShopCatalog = {
    {
        id = "cos_head_duskmask",
        name = "Dusk Mask",
        price = 850,
        category = "Cosmetic",
        slot = "head",
        rarity = "Common",
        tags = { "horror", "mask" },
    },
    {
        id = "cos_head_mortisveil",
        name = "Mortis Veil",
        price = 2400,
        category = "Cosmetic",
        slot = "head",
        rarity = "Rare",
        tags = { "horror", "veil" },
    },
    {
        id = "cos_body_gravetunic",
        name = "Grave Tunic",
        price = 1250,
        category = "Cosmetic",
        slot = "body",
        rarity = "Common",
        tags = { "outfit" },
    },
    {
        id = "cos_body_scarletritual",
        name = "Scarlet Ritual Coat",
        price = 3800,
        category = "Cosmetic",
        slot = "body",
        rarity = "Epic",
        tags = { "outfit", "ritual" },
    },
    {
        id = "cos_outfit_fieldinvestigator",
        name = "Field Investigator Set",
        price = 5100,
        category = "Cosmetic",
        slot = "outfit",
        rarity = "Epic",
        tags = { "bundle", "investigator" },
    },
    {
        id = "cos_accessory_wardingcharm",
        name = "Warding Charm",
        price = 700,
        category = "Cosmetic",
        slot = "accessory",
        rarity = "Common",
        tags = { "accessory", "charm" },
    },
    {
        id = "cos_accessory_spiritlantern",
        name = "Spirit Lantern",
        price = 1800,
        category = "Cosmetic",
        slot = "accessory",
        rarity = "Rare",
        tags = { "accessory", "lantern" },
    },
    {
        id = "cos_emote_steadybreath",
        name = "Steady Breath Emote",
        price = 500,
        category = "Cosmetic",
        slot = "emote",
        rarity = "Common",
        tags = { "emote" },
    },
    {
        id = "cos_emote_ghostmock",
        name = "Ghost Mock Emote",
        price = 1200,
        category = "Cosmetic",
        slot = "emote",
        rarity = "Rare",
        tags = { "emote" },
    },
    {
        id = "eq_sanitypill_standard",
        name = "Sanity Pill (Standard)",
        price = 300,
        category = "Equipment",
        rarity = "Common",
        tags = { "consumable", "sanity" },
    },
    {
        id = "eq_sanitypill_advanced",
        name = "Sanity Pill (Advanced)",
        price = 900,
        category = "Equipment",
        rarity = "Rare",
        tags = { "consumable", "sanity" },
    },
    {
        id = "eq_saltbag_reinforced",
        name = "Reinforced Salt Bag",
        price = 650,
        category = "Equipment",
        rarity = "Common",
        tags = { "tool" },
    },
    {
        id = "eq_flashlight_uv",
        name = "UV Flashlight Mk2",
        price = 1500,
        category = "Equipment",
        rarity = "Rare",
        tags = { "tool", "uv" },
    },
    {
        id = "eq_spiritbox_modded",
        name = "Modded Spirit Box",
        price = 2900,
        category = "Equipment",
        rarity = "Epic",
        tags = { "tool", "spiritbox" },
    },
}

return ShopCatalog
