return {
    mapName = "Abandoned Palace",
    mapCategory = "Investigation",
    mapSize = "Large",
    mapDimensions = {
        width = 180,
        depth = 180,
        floors = 1,
    },
    spawnPoints = {
        "PlayerSpawn_1",
        "PlayerSpawn_2",
        "PlayerSpawn_3",
        "PlayerSpawn_4",
    },
    rooms = {
        "GrandHall",
        "RoyalCorridor",
        "DiningHall",
        "Library",
        "GuestRoomA",
        "GuestRoomB",
        "GuestRoomC",
        "ServantRoomA",
        "ServantRoomB",
        "ServantRoomC",
        "Basement",
        "Courtyard",
        "Armory",
        "Chapel",
        "Ballroom",
        "Observatory",
        "StorageWing",
        "CeremonyRoom",
    },
    hideSpotRooms = {
        "StorageWing",
        "ServantRoomA",
        "ServantRoomB",
    },
    ghostRoomCandidates = {
        "Library",
        "GuestRoomA",
        "DiningHall",
        "Basement",
        "RoyalCorridor",
    },
    evidenceSpawnPoints = {
        "EvidenceNode_1",
        "EvidenceNode_2",
        "EvidenceNode_3",
        "EvidenceNode_4",
        "EvidenceNode_5",
        "EvidenceNode_6",
        "EvidenceNode_7",
        "EvidenceNode_8",
        "EvidenceNode_9",
        "EvidenceNode_10",
        "EvidenceNode_11",
        "EvidenceNode_12",
        "EvidenceNode_13",
        "EvidenceNode_14",
    },
    interactionObjects = {
        "Doors",
        "Lights",
        "Props",
        "Electronics",
        "Windows",
        "InteractionPoints",
        "SafeZones",
    },
    visualTheme = {
        ambiance = "ColdRoyal",
        fogStart = 30,
        fogEnd = 150,
        flickerChance = 0.2,
    },
    traversal = {
        recommendedPathWidth = 12,
        roamingRadius = { min = 35, max = 45 },
        huntDetectionRange = 40,
    },
}
