return {
    mapName = "Empty Building",
    mapCategory = "Investigation",
    mapSize = "MediumSmall",
    mapDimensions = {
        width = 100,
        depth = 100,
        floors = 2,
    },
    spawnPoints = {
        "PlayerSpawn_1",
        "PlayerSpawn_2",
        "PlayerSpawn_3",
        "PlayerSpawn_4",
    },
    rooms = {
        "Lobby",
        "SecurityRoom",
        "Storage",
        "ElectricalRoom",
        "OfficeA",
        "OfficeB",
        "Bathroom1",
        "WorkspaceOpen",
        "MeetingRoom",
        "ServerRoom",
        "ArchiveRoom",
        "Bathroom2",
        "StaircaseNorth",
        "StaircaseSouth",
    },
    hideSpotRooms = {
        "Storage",
        "ArchiveRoom",
        "SecurityRoom",
    },
    ghostRoomCandidates = {
        "ServerRoom",
        "ArchiveRoom",
        "Storage",
        "MeetingRoom",
        "ElectricalRoom",
    },
    evidenceSpawnPoints = {
        "EvidenceNode_1",
        "EvidenceNode_2",
        "EvidenceNode_3",
        "EvidenceNode_4",
        "EvidenceNode_5",
        "EvidenceNode_6",
        "EvidenceNode_7",
        "EvidenceNode_8",
        "EvidenceNode_9",
    },
    interactionObjects = {
        "Doors",
        "Lights",
        "Props",
        "Electronics",
        "Windows",
        "InteractionPoints",
        "SafeZones",
    },
    visualTheme = {
        ambiance = "CorporateDerelict",
        fogStart = 30,
        fogEnd = 150,
        flickerChance = 0.2,
    },
    traversal = {
        recommendedPathWidth = 9,
        roamingRadius = { min = 25, max = 30 },
        huntDetectionRange = 30,
    },
}
