return {
    mapName = "Haunted House",
    mapCategory = "Investigation",
    mapSize = "Medium",
    mapDimensions = {
        width = 140,
        depth = 140,
        floors = 2,
    },
    spawnPoints = {
        "PlayerSpawn_1",
        "PlayerSpawn_2",
        "PlayerSpawn_3",
        "PlayerSpawn_4",
    },
    rooms = {
        "LivingRoom",
        "Kitchen",
        "DiningRoom",
        "Bathroom1",
        "Bedroom1",
        "Bedroom2",
        "HallwayMain",
        "ClosetA",
        "ClosetB",
        "Attic",
        "Basement",
        "StairHall",
    },
    ghostRoomCandidates = {
        "Attic",
        "Basement",
        "LivingRoom",
        "Bedroom1",
        "Bedroom2",
    },
    evidenceSpawnPoints = {
        "EvidenceNode_1",
        "EvidenceNode_2",
        "EvidenceNode_3",
        "EvidenceNode_4",
        "EvidenceNode_5",
        "EvidenceNode_6",
        "EvidenceNode_7",
        "EvidenceNode_8",
        "EvidenceNode_9",
        "EvidenceNode_10",
    },
    interactionObjects = {
        "Doors",
        "Lights",
        "Props",
        "InteractionPoints",
        "SafeZones",
    },
    visualTheme = {
        ambiance = "DomesticDecay",
        fogStart = 30,
        fogEnd = 150,
        flickerChance = 0.2,
    },
    traversal = {
        recommendedPathWidth = 10,
        roamingRadius = { min = 25, max = 30 },
        huntDetectionRange = 30,
    },
}
