return {
	mapName = "Haunted House",
	mapCategory = "Investigation",
	mapSize = "Medium",
	mapDimensions = {
		width = 160,
		depth = 180,
		floors = 2,
	},
	rooms = {
		"Foyer",
		"DiningRoom",
		"Bathroom1",
		"StairHall",
		"LaundryRoom",
		"Bathroom2",
		"Kitchen",
		"Pantry",
		"LivingRoom",
		"Garage",
		"HallwayMain",
		"Bathroom3",
		"Bedroom1",
		"ClosetA",
		"Bedroom2",
		"LinenCloset",
		"Bedroom3",
		"ClosetB",
		"Bathroom4",
		"BonusRoom",
	},
	hideSpotRooms = {
		"ClosetA",
		"ClosetB",
	},
	ghostRoomCandidates = {
		"LivingRoom",
		"Kitchen",
		"Garage",
		"Bedroom1",
		"Bedroom2",
		"Bedroom3",
		"BonusRoom",
	},
	evidenceSpawnPoints = {
		"EvidenceNode_1",
		"EvidenceNode_2",
		"EvidenceNode_3",
		"EvidenceNode_4",
		"EvidenceNode_5",
		"EvidenceNode_6",
		"EvidenceNode_7",
		"EvidenceNode_8",
		"EvidenceNode_9",
		"EvidenceNode_10",
		"EvidenceNode_11",
		"EvidenceNode_12",
		"EvidenceNode_13",
		"EvidenceNode_14",
	},
	interactionObjects = {
		"Doors",
		"Lights",
		"Props",
		"Electronics",
		"Windows",
		"InteractionPoints",
		"SafeZones",
	},
	visualTheme = {
		ambiance = "DomesticDecay",
		fogStart = 30,
		fogEnd = 150,
		flickerChance = 0.2,
	},
	traversal = {
		recommendedPathWidth = 10,
		roamingRadius = { min = 25, max = 32 },
		huntDetectionRange = 30,
	},
}
