return {
    mapName = "Lobby Social Hub",
    mapCategory = "Lobby",
    mapSize = "Hub",
    mapDimensions = {
        width = 420,
        depth = 420,
        floors = 1,
        pathWidth = 12,
    },
    spawnPoints = {
        "PlayerSpawn_1",
        "PlayerSpawn_2",
        "PlayerSpawn_3",
        "PlayerSpawn_4",
    },
    rooms = {
        "MainHubPlaza",
        "NorthEvidenceBuilding",
        "EastShopBuilding",
        "WestPartyZone",
        "SouthSocialGarden",
        "SouthEastFlexZone",
    },
    ghostRoomCandidates = {
        "NorthEvidenceBuilding",
        "SouthEastFlexZone",
    },
    evidenceSpawnPoints = {
        "EvidenceNode_1",
        "EvidenceNode_2",
        "EvidenceNode_3",
        "EvidenceNode_4",
        "EvidenceNode_5",
        "EvidenceNode_6",
        "EvidenceNode_7",
        "EvidenceNode_8",
        "EvidenceNode_9",
        "EvidenceNode_10",
        "EvidenceNode_11",
        "EvidenceNode_12",
    },
    interactionObjects = {
        "Doors",
        "Lights",
        "ShopNPC",
        "QueueTrigger",
        "PartyBoard",
        "EvidenceTables",
        "FlexDisplay",
    },
    visualTheme = {
        ambiance = "ColdSocialHorror",
        fogStart = 30,
        fogEnd = 150,
        flickerChance = 0.2,
    },
}
