return {
    mapName = "Studio MMNineteen",
    mapCategory = "Investigation",
    mapSize = "Small",
    mapDimensions = {
        width = 90,
        depth = 90,
        floors = 2,
    },
    spawnPoints = {
        "PlayerSpawn_1",
        "PlayerSpawn_2",
        "PlayerSpawn_3",
        "PlayerSpawn_4",
    },
    rooms = {
        "RecordingRoom",
        "EditingRoom",
        "ControlRoom",
        "FilmStage",
        "StorageRoom",
        "Office",
        "HallwayA",
        "HallwayB",
    },
    hideSpotRooms = {
        "StorageRoom",
    },
    ghostRoomCandidates = {
        "RecordingRoom",
        "ControlRoom",
        "FilmStage",
        "EditingRoom",
    },
    evidenceSpawnPoints = {
        "EvidenceNode_1",
        "EvidenceNode_2",
        "EvidenceNode_3",
        "EvidenceNode_4",
        "EvidenceNode_5",
        "EvidenceNode_6",
        "EvidenceNode_7",
        "EvidenceNode_8",
    },
    interactionObjects = {
        "Doors",
        "Lights",
        "Props",
        "InteractionPoints",
        "SafeZones",
    },
    visualTheme = {
        ambiance = "BroadcastNightmare",
        fogStart = 30,
        fogEnd = 150,
        flickerChance = 0.2,
    },
    traversal = {
        recommendedPathWidth = 8,
        roamingRadius = { min = 20, max = 25 },
        huntDetectionRange = 24,
    },
}
