return {
	mapName = "Studio MMNineteen",
	mapCategory = "Investigation",
	mapSize = "MediumSmall",
	mapDimensions = {
		width = 100,
		depth = 100,
		floors = 3,
	},
	spawnPoints = {
		"PlayerSpawn_1",
		"PlayerSpawn_2",
		"PlayerSpawn_3",
		"PlayerSpawn_4",
	},
	rooms = {
		"FrontPorch",
		"LivingRoom",
		"LaundryRoom",
		"StairHallL1",
		"Kitchen",
		"DiningArea",
		"Bathroom",
		"StairHallL2",
		"UpperHall",
		"Bedroom1",
		"Bedroom2",
		"StairHallL3",
	},
	hideSpotRooms = {
		"LaundryRoom",
		"StairHallL3",
	},
	ghostRoomCandidates = {
		"LivingRoom",
		"Kitchen",
		"Bathroom",
		"Bedroom1",
		"Bedroom2",
	},
	evidenceSpawnPoints = {
		"EvidenceNode_1",
		"EvidenceNode_2",
		"EvidenceNode_3",
		"EvidenceNode_4",
		"EvidenceNode_5",
		"EvidenceNode_6",
		"EvidenceNode_7",
		"EvidenceNode_8",
		"EvidenceNode_9",
		"EvidenceNode_10",
		"EvidenceNode_11",
		"EvidenceNode_12",
	},
	interactionObjects = {
		"Doors",
		"Lights",
		"Props",
		"Electronics",
		"Windows",
		"InteractionPoints",
		"SafeZones",
	},
	visualTheme = {
		ambiance = "BroadcastNightmare",
		fogStart = 30,
		fogEnd = 150,
		flickerChance = 0.2,
	},
	traversal = {
		recommendedPathWidth = 9,
		roamingRadius = { min = 20, max = 25 },
		huntDetectionRange = 24,
	},
}
