return {
    Core = {
        "ConfigLoader",
        "GameConfigSystem",
        "GhostDatabaseSystem",
        "MapConfigSystem",
        "EvidenceConfigSystem",
        "DifficultyConfigSystem",
        "ContractConfigSystem",
        "DataPersistence",
        "ProfileSystem",
        "EconomySystem",
        "RankedSystem",
        "ContractSystem",
        "MatchSystem",
        "MapInteractionSystem",
        "ToolInteractionSystem",
        "ToolSignalProcessingSystem",
        "EvidenceToolSystem",
        "MapEventSystem",
        "GhostModifierSystem",
        "AggressionSystem",
        "SanitySystem",
        "GhostSystem",
        "EvidenceSystem",
        "InvestigationSystem",
        "JournalSystem",
        "EvidenceJournalSystem",
        "GhostDeductionJournal",
        "HorrorDirector",
        "EscalationTimerSystem",
        "RandomJumpscareSystem",
        "LobbySocialHub",
    },

    Gameplay = {
        "HuntSystem",
        "HuntPhaseController",
        "HuntEscapeSystem",
        "PlayerSurvivalSystem",
        "PlayerHealthSystem",
        "HidingSystem",
        "ClosetHidingMechanic",
        "GhostChaseSystem",
        "GhostPathingSystem",
        "PlayerDeathSystem",
        "DeathStateSystem",
        "SpectatorModeSystem",
        "SpectatorCameraSystem",
        "MatchResultSystem",
        "RewardCalculationSystem",
        "ContractCompletionSystem",
        "GameplayLoopController",
    },

    AI = {},

    Player = {
        "SystemIntegrationController",
        "EngineStartupValidator",
        "DependencyVerificationSystem",
        "RuntimeIntegritySystem",
        "SystemDiagnosticsController",
        "ProductionSafetySystem",
        "FinalEngineBootstrap",
    },

    Economy = {},

    Social = {},
}
