return {
    Core = {
        "ConfigLoader",
        "GameConfigSystem",
        "ContentUpdatePipelineSystem",
        "LiveContentOpsSystem",
        "GhostDatabaseSystem",
        "MapConfigSystem",
        "EventMapRotationSystem",
        "EvidenceConfigSystem",
        "DifficultyConfigSystem",
        "ContractConfigSystem",
        "DataPersistence",
        "ProfileSystem",
        "PlatformSupportSystem",
        "InventorySystem",
        "ProgressionSystem",
        "RoyalPassSystem",
        "EconomySystem",
        "SocialCommerceSystem",
        "RankedSystem",
        "MatchmakingQualitySystem",
        "SeasonalEventSystem",
        "ContractSystem",
        "LobbySystem",
        "MatchSystem",
        "MapInteractionSystem",
        "ToolInteractionSystem",
        "FlashlightSyncSystem",
        "ToolSignalProcessingSystem",
        "EvidenceToolSystem",
        "MapEventSystem",
        "GhostModifierSystem",
        "AggressionSystem",
        "SanitySystem",
        "GhostSystem",
        "EvidenceSystem",
        "InvestigationSystem",
        "JournalSystem",
        "EvidenceJournalSystem",
        "GhostDeductionJournal",
        "HorrorDirector",
        "EscalationTimerSystem",
        "DynamicInvestigationEventSystem",
        "RandomJumpscareSystem",
        "LobbySocialHub",
        "GlobalOperationsSystem",
    },

    Gameplay = {
        "HuntSystem",
        "HuntPhaseController",
        "HuntEscapeSystem",
        "PlayerSurvivalSystem",
        "PlayerHealthSystem",
        "HidingSystem",
        "ClosetHidingMechanic",
        "GhostChaseSystem",
        "GhostPathingSystem",
        "PlayerDeathSystem",
        "DeathStateSystem",
        "SpectatorModeSystem",
        "SpectatorCameraSystem",
        "MatchResultSystem",
        "RewardCalculationSystem",
        "ContractCompletionSystem",
        "GameplayLoopController",
    },

    AI = {},

    Player = {
        "PlayerEngagementSystem",
        "PlayerReputationSystem",
        "ModerationOperationsSystem",
        "SystemIntegrationController",
        "EngineStartupValidator",
        "DependencyVerificationSystem",
        "RuntimeIntegritySystem",
        "SystemDiagnosticsController",
        "ProductionSafetySystem",
        "FinalEngineBootstrap",
    },

    Economy = {
        "DailyContractSystem",
        "WeeklyChallengeSystem",
    },

    Social = {
        "SocialEmoteSystem",
        "OperationsQASystem",
    },
}
